### PR TITLE
OHLCV values at the closing end of each timestamp

### PR DESCRIPTION
**Pull request by multidis**
Issue #6

### CODE REVIEW

**Comment by rosspalmer** [comment]
The change to `cron` absolutely needs to happen. At this point the `cron` class simply works and is not built to be reliable, which needs to change.

I think I understand why you would want to label with the end bracket in the live context but not entirely sure if you would want to build a history that way. Daily frequencies for example are shift by a whole day.

Its really easy to `.shift()` for historical data so what's best live is the question.

**Comment by rosspalmer** [comment]
If you have any references I could read, that would be awesome

**Comment by multidis** [comment]
I guess there are examples that can be found with both types of indexing, left and right. There does not seem to be any fundamental arguments to choose either way, but seems to me that when using close prices it makes sense if they are matched with the volumes that moved the market to those close prices, hence the right-side indexing. A more general solution to consider would be some optional argument for the user to choose right vs left bin with a default selection.

**Comment by multidis** [comment]
Regarding cron - what other potential error sources are there to watch for? May be there is some generic python module that schedules function calls with error handling? (That seems to be such a common task).

**Comment by rosspalmer** [comment]
I set an optional parameter `label='left'` for the time being in this commit and should be available in any conversion function.

[Commit](https://github.com/rosspalmer/bitQuant/commit/7cc92480d1007c09380cce6d0032c77c1632a5dc)

**Pull request merged**
